#pragma once

#include <memory>
#include <utility>
#include <algorithm>
#include <functional>
#include <string>
#include <sstream>
#include <fstream>
#include <iostream>
#include <array>
#include <vector>
#include <unordered_map>
#include <unordered_set>
#include <stdexcept>
#include <limits>
#include <chrono>
#include <climits>
#include <bitset>
#include <iterator>
#include <queue>
#include <tuple>
#include <type_traits>
#include <any>
#include <list>
#include <variant>
#include <initializer_list>
#include <filesystem>
#include <iomanip>
#include <numeric>
#include <mutex>
#include <condition_variable>
#include <optional>
#include <limits.h>
#include <expected>
#include <optional>

#include <cstddef>
#include <cstdint>
#include <cmath>
#include <cctype>
#include <cstring>

#include "Core/Log.hpp"
#include "Core/Assert.hpp"
#include "Core/PlatformDetection.hpp"
#include "Core/Types.hpp"
#include "Core/Limits.hpp"
#include "Debug/Debug.hpp"